spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.6.128:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**.*xml #配置mapper扫描接口路径
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-field: falag #全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.atguigu.gulimall: debug

