spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast-master
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}